management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: logging
  sleuth:
    opentracing:
      enabled: false

logging.level.com.nathandeamer.logging: TRACE