management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: logging
  sleuth:
    opentracing:
      enabled: true
    propagation:
      type: b3,w3c
  zipkin:
    base-url: http://simplest-collector.default.svc.cluster.local:9411/